name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pip
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pip'
      - name: Install fusesoc
        run: pip install -e fusesoc
      - name: Run fusesoc
        run: fusesoc --cores-root . run --target lint $(fusesoc --cores-root . list-cores | tail -1 | awk '{print$1}')
